services:
  # Airflow Services Base
  airflow_common_base:
    image: apache/airflow:latest
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@airflow_db:5432/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW_VAR_KAFKA_BOOTSTRAP_SERVER: kafka_broker:9092
      AIRFLOW_VAR_COMMENTS_TOPIC_NAME: ${COMMENTS_TOPIC_NAME}
      AIRFLOW_VAR_CASSANDRA_HOST: ${CASSANDRA_HOST}
      AIRFLOW_VAR_CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE}
      AIRFLOW_VAR_FETCHING_INFO_TABLE: ${FETCHING_INFO_TABLE}
    env_file:
      - .env.secrets
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/requirements.txt:/opt/airflow/requirements.txt
