services:
  # Airflow PostgreSQL Database
  airflow_db:
    image: postgres:16.0
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  # Airflow Init
  airflow_init:
    extends:
      file: base-services.yml
      service: airflow_common_base
    entrypoint: bash -c "airflow db init && airflow users create --role Admin --username admin --email admin --firstname admin --lastname admin --password admin"
    depends_on:
      - airflow_db
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  # Airflow Webserver
  airflow_webserver:
    extends:
      file: base-services.yml
      service: airflow_common_base
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka_broker:9092
      - COMMENTS_TOPIC_NAME=${COMMENTS_TOPIC_NAME}
    env_file:
      - .env.secrets
    entrypoint: bash -c "airflow db upgrade && pip install -r requirements.txt && airflow webserver"
    restart: always
    depends_on:
      - airflow_init
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  # Airflow Scheduler
  airflow_scheduler:
    extends:
      file: base-services.yml
      service: airflow_common_base
    entrypoint: bash -c "airflow db upgrade && pip install -r requirements.txt && airflow scheduler"
    restart: always
    depends_on:
      - airflow_webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-scheduler.pid ]"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Kafka Broker
  kafka_broker:
    image: apache/kafka:latest
    hostname: kafka_broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 2
      COMMENTS_TOPIC_NAME: ${COMMENTS_TOPIC_NAME}
    volumes:
      - ./kafka/scripts/:/opt/kafka/scripts

volumes:
  postgres-db-volume:
  spark_data:
